namespace CapyBro.Models;

/// <summary>
/// Result tier of an OpenRouter API-key validity probe.  Drives the
/// inline status indicator under the API-key field on
/// <c>GeneralTab.xaml</c>.  The view binds five mutually-exclusive
/// "is in state X" booleans (auto-generated by the
/// <c>[ObservableProperty]</c> source generator on
/// <c>GeneralTabViewModel.ApiKeyState</c>) so each row in the
/// indicator can show the right glyph + text without a value
/// converter dance.
///
/// Why an enum rather than a free-form status string: the indicator
/// has to render a tinted glyph (Check/X/Loader/AlertTriangle) per
/// state and the brushes need to be picked at the binding site, not
/// from a Translator key — five named states keep the surface
/// finite and exhaustive, so adding a sixth (e.g. "Rate limited")
/// later is an additive change to this enum + one XAML row +
/// matching computed bool, no rewiring.
/// </summary>
public enum ApiKeyValidationState
{
    /// <summary>
    /// No key in the field, or the user is mid-edit and validation
    /// has been reset pending the next debounce tick.  Indicator is
    /// hidden entirely so an empty field doesn't display a "wait..."
    /// placeholder that never resolves.
    /// </summary>
    None,

    /// <summary>
    /// /credits request is in flight.  Indicator shows a muted
    /// Loader2 glyph + "Перевіряємо..." caption.  Set immediately
    /// when validation kicks off so the user sees feedback within
    /// a single frame of the debounce timer firing.
    /// </summary>
    Checking,

    /// <summary>
    /// /credits returned 200 — the key authenticates successfully
    /// against OpenRouter.  Indicator shows a green Check glyph +
    /// "Ключ дійсний" caption.  The user can immediately try a
    /// hotkey-driven improvement with confidence the request will
    /// reach the model.
    /// </summary>
    Valid,

    /// <summary>
    /// /credits returned 401 (or BuildRequest rejected the key
    /// shape — e.g. CR/LF in the pasted value).  Indicator shows a
    /// red X glyph + "Ключ недійсний" caption.  Distinct from
    /// <see cref="NetworkError"/> so the user knows the problem
    /// is the key itself, not connectivity, and re-pasting from
    /// OpenRouter is the fix.
    /// </summary>
    Invalid,

    /// <summary>
    /// Validation couldn't complete for non-key reasons: timeout,
    /// 5xx, DNS failure, no internet.  Indicator shows a muted
    /// AlertTriangle glyph + "Не вдалося перевірити" caption — we
    /// can't say whether the key is valid, but we don't want to
    /// scare the user into changing a probably-fine key.  The
    /// next debounce tick re-tries automatically.
    /// </summary>
    NetworkError,
}
